#!/bin/bash
manifests="/Users/andrew/Documents/projects/puppet/manifests"
parallel rsync -rl --executability --exclude '.git*' --delete-excluded $manifests ::: krikkit.schwartzmeyer.com: slartibartfast.schwartzmeyer.us:
