#!/bin/sh
# Shamelessly borrowed from boxen

# Make sure all our local dependencies are available.

set -e

# FIX: only sudo if gem home isn't writable

(gem list -i bundler -v '~> 1.3.0' > /dev/null) || {
    gem install bundler -v '~> 1.3.0' --no-rdoc --no-ri
}

# We don't want old config hanging around.

rm -rf .bundle/config
rm -rf .librarian/puppet/config

# Bundle install unless we're already up to date.
bundle install --binstubs bin --path .bundle --quiet "$@"
bundle exec librarian-puppet install
