#!/bin/bash
[[ -e script/push ]] || { echo >&2 "Please cd into manifests"; exit 1; }

echo "Pushing manifests and modules"
./script/push "$@"

echo "Provisioning puppets"
source script/.get_host
parallel ssh {} 'cd manifests && ./script/apply' ::: $(get_host $@)
