#!/bin/bash
[[ -e script/push ]] || { echo >&2 "Please cd into manifests"; exit 1; }

source script/.get_host
parallel rsync -rl --executability --exclude '.git*' --exclude 'ssl' . ::: $(get_host $@)
