#!/bin/bash
[[ -e script/push ]] || { echo >&2 "Please cd into manifests"; exit 1; }
puppets="krikkit.schwartzmeyer.com:manifests slartibartfast.schwartzmeyer.us:manifests"
parallel -j 4 rsync -rl --executability --exclude '.git*' . ::: $puppets
