#!/bin/bash
manifests="/Users/andrew/Documents/projects/puppet/manifests"
parallel -j 4 rsync -rl --executability --exclude '.git*' --exclude 'ssl' --delete-excluded $manifests ::: krikkit.schwartzmeyer.com: slartibartfast.schwartzmeyer.us:
